### PR TITLE
Object Recognition Dynamic Graph Example

### PR DESCRIPTION
**Pull request by faromero**
The first commit add all of the source code, a Makefile, and the input data.
The second commit is one-line modifications each to configure.ac and examples/Makefile.am to build the binaries for the program.

### CODE REVIEW

**Comment by sadjad** [comment]
Hi Franky,

Thanks for the pull request! Could you please take all the output files out? (And ideally, create a `.gitignore` file in the example root directory, ignoring `*.out` files?).

–Sadjad

**Comment by faromero** [comment]
Apologies: the .out files are actually not outputs from this app, they are inputs (outputs from the video decoding pipeline). I can change the `.out` extension to be `.in` if that makes it clearer. I can also add the `.gitignore` for all `.out` files.

**Comment by sadjad** [comment]
Oh, sorry, I didn't realize that. Can you briefly explain the inputs and the outputs of this program before I start reading the code then?

**Comment by faromero** [comment]
Sure: besides the binary, the inputs are files containing objects that were recognized by a neural network. The output of the whole app is a single output file counting how many times a particular object was found, which in this case is a wall. The final output file would contain a single number.

**Comment by sadjad** [comment]
Got it, thanks!

**Pull request closed without merging**
